export const API = {
  HEALTH:   '/api/health',
  AUTH: {
    CALLBACK: '/api/auth/callback',
    LOGOUT:   '/api/auth/logout',
    ME:       '/api/auth/me',
    SIGNUP:   '/api/auth/signup',
    INVITE:   '/api/auth/invite',
    MFA_SETUP:      '/api/auth/mfa/setup',
    MFA_VERIFY:     '/api/auth/mfa/verify',
    INVITE_ACCEPT:  '/api/auth/invite/accept',
  },
  HEALTH_AI: '/api/health/ai',
  PORTAL_FEEDBACK: '/api/portal/feedback',
  PROJECTS:   '/api/projects',
  PROJECT:    (id: string) => `/api/projects/${id}`,
  BRIEFS:     (projectId: string) => `/api/projects/${projectId}/briefs`,
  BRIEF:      (projectId: string, briefId: string) => `/api/projects/${projectId}/briefs/${briefId}`,
  BRIEF_SESSIONS:  (briefId: string) => `/api/briefs/${briefId}/sessions`,
  BRIEF_QUESTIONS: (briefId: string, sessionId: string) => `/api/briefs/${briefId}/sessions/${sessionId}/questions`,
  ESTIMATES:  (projectId: string) => `/api/projects/${projectId}/estimates`,
  ESTIMATE:   (projectId: string, id: string) => `/api/projects/${projectId}/estimates/${id}`,
  TASKS:      (projectId: string) => `/api/projects/${projectId}/tasks`,
  TASK:       (projectId: string, taskId: string) => `/api/projects/${projectId}/tasks/${taskId}`,
  SCOPE:      (projectId: string) => `/api/projects/${projectId}/scope`,
  CHANGE_ORDERS:  (projectId: string) => `/api/projects/${projectId}/change-orders`,
  CHANGE_ORDER:   (projectId: string, id: string) => `/api/projects/${projectId}/change-orders/${id}`,
  HANDOFF:        (projectId: string) => `/api/projects/${projectId}/handoff`,
  HANDOFF_SEARCH: (projectId: string) => `/api/projects/${projectId}/handoff/search`,
  TIMESHEET:      (projectId: string) => `/api/projects/${projectId}/timesheet`,
  PROFITABILITY:  (projectId: string) => `/api/projects/${projectId}/profitability`,
  APPROVALS:      (projectId: string) => `/api/projects/${projectId}/approvals`,
  APPROVAL:       (projectId: string, id: string) => `/api/projects/${projectId}/approvals/${id}`,
  MEMBERS:        (projectId: string) => `/api/projects/${projectId}/members`,
  NOTIFICATIONS:        '/api/notifications',
  NOTIFICATION:         (id: string) => `/api/notifications/${id}`,
  NOTIFICATION_READ_ALL: '/api/notifications/read-all',
  EVENTS:  '/api/events',
  PORTAL:  '/api/portal',
  PORTAL_PROJECT: (id: string) => `/api/portal/${id}`,
  BRIEF_PRD: (briefId: string) => `/api/briefs/${briefId}/prd`,
  BRIEF_PRD_VERSIONS: (briefId: string) => `/api/briefs/${briefId}/prd/versions`,
} as const
